name: Create Release Branch

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    name: Prepare a release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
        name: Checkout the code repository
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_PAT_TOKEN }}

      - run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
        name: Configure Git into the runner

      - uses: oven-sh/setup-bun@v2
        name: Install bun runtime
        with:
          bun-version-file: '.bun-version'

      - run: bun install --frozen-lockfile
        name: Install dependencies

      - run: |
          OLD_VERSION=$(jq .version package.json)

          bun changeset version
          NEW_VERSION=$(jq .version package.json)

          echo "old_version=${OLD_VERSION}" >> $GITHUB_OUTPUT
          echo "new_version=${NEW_VERSION}" >> $GITHUB_OUTPUT
        name: Bump release version
        id: bump

      - run: |
          bun run format:fix
          bun run lint:fix

          git add .
          git commit -n -m "chore(release): v${{ steps.bump.outputs.new_version }}"
          git push origin main -f --no-verify
        name: Commit version bump to main
        if: ${{ steps.bump.outputs.old_version != steps.bump.outputs.new_version }}

      - run: |
          git checkout -b release/v${{ steps.bump.outputs.new_version }}
          git push origin release/v${{ steps.bump.outputs.new_version }} -f --no-verify
        name: Create release branch
        if: ${{ steps.bump.outputs.old_version != steps.bump.outputs.new_version }}
